[profile.default]
auto_detect_solc = false
solc = "0.8.16"
gas_reports = ["*"]
optimizer = true
optimizer_runs = 1_000_000
src = "src"
out = "out"
libs = ["lib"]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# I like this template a lot: https://github.com/PaulRBerg/foundry-template/blob/main/foundry.toml
